#!/bin/bash

#Identify the default gateway in the routing table

#netstat -rn show Kernel IP routing table
#route - Manually manipulate the routing tables
#	get: Lookup and display the route for a destination
#	- n: Print host and network names

route -n get default | grep gateway

