#!/bin/bash

#Identify the ip address of the DNS that responds to the following url: who.int

#nslookup - query Internet name srvers interactively
#DNS - Domain Name System
# traduit un nom de domaine en IP 
nslookup who.int
