#!/bin/bash

#Use the output of the previous command to find the name and IP address of the
#device that make the link between you (local network) and the outside world


#need more info
# nat - Stateless native address translation action

